// useToast — global toast store. Render <NToaster /> once near the app root, then
// push messages from anywhere via useToast() (success / error / warning / info).
import { reactive } from "vue";

/** Toast presentation tones used by push and the convenience methods. */
export type ToastTone = "ok" | "info" | "warn" | "danger";

/** Options spread over the defaults when a toast is added. */
export interface ToastOptions {
    /** Presentation tone; defaults to ok when omitted. */
    tone?: ToastTone;
    /** Heading; defaults to an empty string when omitted from push options. */
    title?: string;
    /** Body; defaults to an empty string when omitted from push options. */
    msg?: string;
    /**
     * Auto-dismiss delay in milliseconds: 7000 for danger, 5000 for warn, otherwise
     * 3600. Zero, negative, or NaN values do not start a timer; no validation is applied.
     */
    duration?: number;
}

/**
 * Mutable toast record in the shared reactive list, including timer bookkeeping.
 */
export interface Toast extends ToastOptions {
    /** Module-wide identifier, generated by incrementing a counter starting at zero. */
    id: number;
    /** Presentation tone after options have been applied. */
    tone: ToastTone;
    /** Heading after options have been applied. */
    title: string;
    /** Body text after defaults have been applied. */
    msg: string;
    /** Configured dismissal delay in milliseconds. */
    duration: number;
    /** Host timer handle while armed, or null when unarmed. */
    timer: ReturnType<typeof setTimeout> | null;
    /** Epoch milliseconds of the latest timer start; zero before first arming. */
    startedAt: number;
    /** Milliseconds saved for the next resume; may be nonpositive after pausing. */
    remaining: number;
}

// Single shared list of active toasts (module-level singleton).
const state = reactive<{ toasts: Toast[] }>({ toasts: [] });
let uid = 0;

// Arm/disarm a toast's auto-dismiss timer. `remaining` tracks the time left so
// pauseAll/resumeAll (pointer/focus inside the toaster) can stop and resume it.
function arm(t: Toast) {
    t.startedAt = Date.now();
    t.timer = setTimeout(() => dismiss(t.id), t.remaining);
}

function disarm(t: Toast) {
    if (t.timer) {
        clearTimeout(t.timer);
        t.timer = null;
    }
}

/**
 * Append a toast to the shared list and arm its auto-dismiss timer when duration > 0.
 * A string supplies only the title. Defaults are ok, empty title/message, and
 * 3600 ms (7000 for danger, 5000 for warn). Null/missing options at runtime act
 * as an empty object. Undefined fields use their documented defaults.
 * Durations and tones are not validated; positive delays use host timer semantics.
 * Newly added toasts start timers even after pauseAll has been called.
 * @param opts - Heading text or toast options.
 * @returns The new toast's module-wide incrementing identifier.
 */
function push(opts: string | ToastOptions): number {
    const o = typeof opts === "string" ? { title: opts } : opts || {};
    const tone = o.tone || "ok";
    const defaultDuration = tone === "danger" ? 7000 : tone === "warn" ? 5000 : 3600;
    const t: Toast = {
        id: ++uid,
        tone,
        title: o.title ?? "",
        msg: o.msg ?? "",
        // danger/warn linger longer — errors need more reading time before they
        // auto-dismiss (WCAG 2.2.1); ok/info stay transient. Explicit `duration` wins.
        duration: o.duration ?? defaultDuration,
        timer: null,
        startedAt: 0,
        remaining: 0,
    };

    t.remaining = t.duration;
    state.toasts.push(t);

    // Schedule auto-dismiss; keep the timer on the toast so manual dismiss can cancel it.
    if (t.duration > 0) arm(t);
    return t.id;
}

/**
 * Remove the first toast with the exact id and cancel its timer if armed.
 * Unknown identifiers, including zero in an unmodified store, do nothing.
 * @param id - Identifier returned by push or a convenience method.
 * @returns Nothing.
 */
function dismiss(id: number) {
    const i = state.toasts.findIndex((t) => t.id === id);
    if (i > -1) {
        disarm(state.toasts[i]);
        state.toasts.splice(i, 1);
    }
}

/**
 * Cancel every armed timer and subtract elapsed time from its remaining time.
 * Repeated calls skip unarmed timers. There is no persistent paused flag, so
 * this affects only timers already armed at the time of the call.
 * @returns Nothing.
 */
function pauseAll() {
    for (const t of state.toasts) {
        if (t.timer) {
            t.remaining -= Date.now() - t.startedAt;
            disarm(t);
        }
    }
}
/**
 * Restart unarmed timers only when duration and remaining time are both positive.
 * Toasts with exhausted remaining time stay in the list without a timer.
 * @returns Nothing.
 */
function resumeAll() {
    for (const t of state.toasts) {
        if (t.duration > 0 && !t.timer && t.remaining > 0) arm(t);
    }
}

/**
 * Access the module-wide toast store, shared across callers, apps, and SSR requests.
 * Render NToaster once to display the list. Calling this function adds no toast
 * and registers no unmount cleanup; dismiss cancels individual toast timers.
 * @returns The shared mutable reactive list and toast/timer controls.
 */
export function useToast() {
    return {
        /** Shared mutable list; use dismiss to remove entries and cancel their timers. */
        toasts: state.toasts,
        push,
        dismiss,
        pauseAll,
        resumeAll,
        /**
         * Add an ok toast with a 3600 ms auto-dismiss timer.
         * @param title - Toast heading.
         * @param msg - Optional body; omission stores an empty string.
         * @returns The new toast identifier.
         */
        success: (title: string, msg?: string) => push({ tone: "ok", title, msg }),
        /**
         * Add a danger toast with a 7000 ms auto-dismiss timer.
         * @param title - Toast heading.
         * @param msg - Optional body; omission stores an empty string.
         * @returns The new toast identifier.
         */
        error: (title: string, msg?: string) => push({ tone: "danger", title, msg }),
        /**
         * Add a warn toast with a 5000 ms auto-dismiss timer.
         * @param title - Toast heading.
         * @param msg - Optional body; omission stores an empty string.
         * @returns The new toast identifier.
         */
        warning: (title: string, msg?: string) => push({ tone: "warn", title, msg }),
        /**
         * Add an info toast with a 3600 ms auto-dismiss timer.
         * @param title - Toast heading.
         * @param msg - Optional body; omission stores an empty string.
         * @returns The new toast identifier.
         */
        info: (title: string, msg?: string) => push({ tone: "info", title, msg }),
    };
}
